### ISSUE TITLE
Update profile page

### ISSUE THREAD

**Issue by franck-fourel** [mdblp/blip#15]
- hide email and password fields

**Comment by franck-fourel** [comment]
- no change for the name field 
- email is read-only
- password fields are hidden

**Comment by franck-fourel** [comment]
This profile page change should be conditioned by environment variable defined in configuration file.

**Comment by ysdw** [comment]
Do we keep saving the language too ?

**Comment by franck-fourel** [comment]
yep, the language has to be there. it should be controlled by the I18N_ENABLED variable.
while the other features have to be controlled by an other variable
