### ISSUE TITLE
traduction/tendances journalier

### ISSUE THREAD

**Issue by tiffany30200** [mdblp/blip#61]
quand on clique une note le descriptif de la note est en anglais

**Comment by franck-fourel** [comment]
The "new note" label was not translated. 
This one may require more work to fix it.

**Comment by franck-fourel** [comment]
Peux-tu me donner un exemple, je ne comprends pas @tiffany30200

**Comment by tiffany30200** [comment]
quand tu pointes ta souris sur new note, la Date est en format anglais
