### ISSUE TITLE
Hide Upload link for people using the Diabeloop device.

### ISSUE THREAD

**Issue by franck-fourel** [mdblp/blip#9]
- _version#1_ hide the link in header for all users based on a configuration file 
- _version#2_ add a status in profile data for people suing Diabeloop device

**Comment by ysdw** [comment]
PR done for version#1
Need explanations for version#2.

**Comment by franck-fourel** [comment]
1. Let's stay with version#1 
2. NoData page: hide all the content related to uploader; patientdata.js
3. In the patients/{userid}/share page: hide the "allow uploading" checkbox

**Comment by ysdw** [comment]
Fix done
